name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Plugins
        run: |
          chmod +x gradlew
          ./gradlew make makePluginsJson
          
          # Fix the URL inside the JSON
          sed -i 's|https://raw.githubusercontent.com/android-bench-ibm/cloudstream-big-buck-bunny-extension/builds|https://android-bench-ibm.github.io/cloudstream-big-buck-bunny-extension|g' build/plugins.json
          
          # Create a clean folder for deployment
          mkdir -p deploy
          
          # FIX: Stop GitHub from blocking .cs3 files
          touch deploy/.nojekyll
          
          # Copy files over
          cp **/build/*.cs3 deploy/
          cp build/plugins.json deploy/